# cargo-release 配置

allow-branch = ["main", "master"]
tag = true
tag-prefix = ""
push = false
publish = false
consolidate-commits = true

dev-version = false


pre-release-commit-message = "Release {{crate_name}} {{version}}"
