# cargo-release 配置

allow-branch = ["main", "master"]
tag = true
tag-name = "v{{version}}"
push = true
publish = true
consolidate-commits = true

pre-release-commit-message = "Release {{crate_name}} {{version}}"
